apiVersion: v2
name: worker
description: A Helm chart for the Neosync Management Api
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version.
#
# This is changed automatically to the tag by the github workflow.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 'v0'
# This is the version number of the application being deployed.

# This is changed automatically to the tag by the github workflow.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
appVersion: 'v0'
