version: 2
updates:
  # Enable version updates for go
  - package-ecosystem: "gomod"
    schedule:
      interval: "daily"
    labels:
      - dependencies
    directory: "/"
    groups:
      golang-minor:
        update-types:
          - minor
          - patch
    reviewers:
      - nickzelei
  - package-ecosystem: "gomod"
    schedule:
      interval: "daily"
    labels:
      - dependencies
    directory: "tools"
    groups:
      golang-minor:
        update-types:
          - minor
          - patch
    reviewers:
      - nickzelei

  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - minor
          - patch
    reviewers:
      - nickzelei
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "docs"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
    groups:
      npm-all-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    reviewers:
      - nickzelei

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
    reviewers:
      - nickzelei
