version: 2
updates:
  # Enable version updates for go
  - package-ecosystem: 'gomod'
    directory: 'backend'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'gomod'
    directory: 'worker'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'gomod'
    directory: 'cli'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: 'frontend'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: 'docs'
    schedule:
      interval: 'daily'

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
