linters-settings:
  depguard:
    # new configuration
    rules:
      # logger:
      #   deny:
      #     # logging is allowed only by logutils.Log,
      #     # logrus is allowed to use only in logutils package.
      #     - pkg: "github.com/sirupsen/logrus"
      #       desc: logging is allowed only by logutils.Log
  dupl:
    threshold: 150
  funlen:
    lines: -1 # the number of lines (code + empty lines) is not a right metric and leads to code without empty line or one-liner.
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
  gocyclo:
    min-complexity: 20
  gofmt:
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"
  gomnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    ignored-functions:
      - strings.SplitN

  govet:
    check-shadowing: false
    # settings:
    #   printf:
    #     funcs:
    #       - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
    #       - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
    #       - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
    #       - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  revive:
    rules:
      - name: unexported-return
        disabled: true
      # - name: unused-parameter

linters:
  disable-all: true
  enable:
    - bodyclose
    # - depguard
    - dogsled
    # - dupl
    - errcheck
    - forbidigo
    # - funlen
    # - gochecknoinits
    - goconst
    - gocritic
    # - gocyclo
    - gofmt
    - goimports
    # - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    # - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  # don't enable:
  # - asciicheck
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - wsl

issues:
  excluded-dirs:
    - frontend
    - charts
    - docs
    - node_modules
    - backend/gen
  #   # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - lll
        - goconst
        - gosec
    - path: ^mock_.*\.go$
      text: "exclude mock files"

run:
  timeout: 10m
