quiet: False
disable-version-string: True
with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
  github.com/nucleuscloud/neosync/backend/internal/auth/jwt:
    interfaces:
      JwtValidator:
  github.com/nucleuscloud/neosync/backend/internal/auth/client:
    interfaces:
      Interface:
  github.com/nucleuscloud/neosync/backend/internal/authmgmt:
    interfaces:
      Interface:
  github.com/nucleuscloud/neosync/backend/internal/auth/clientcred_token_provider:
    interfaces:
      tokenProvider:
  github.com/nucleuscloud/neosync/backend/internal/auth/authmw:
    interfaces:
      AuthClient:
  github.com/nucleuscloud/neosync/backend/internal/neosyncdb:
    # config:
    interfaces:
      DBTX:
  github.com/nucleuscloud/neosync/backend/gen/go/db:
    # config:
    interfaces:
      Querier:
      DBTX:
  github.com/nucleuscloud/neosync/backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect:
    # config:
    interfaces:
      UserAccountServiceClient:
      JobServiceClient:
      JobServiceHandler:
      ConnectionServiceClient:
      AuthServiceClient:
      TransformersServiceClient:
  github.com/nucleuscloud/neosync/backend/internal/temporal/clientmanager:
    interfaces:
      DB:
      Interface:
      ConfigProvider:
  github.com/nucleuscloud/neosync/backend/gen/go/db/dbschemas/postgresql:
    # config:
    interfaces:
      Querier:
      DBTX:
  github.com/nucleuscloud/neosync/backend/gen/go/db/dbschemas/mysql:
    # config:
    interfaces:
      Querier:
      DBTX:
  github.com/nucleuscloud/neosync/backend/pkg/mssql-querier:
    # config:
    interfaces:
      Querier:
  github.com/nucleuscloud/neosync/backend/pkg/sqlconnect:
    interfaces:
      SqlConnector:
      SqlDbContainer:
  github.com/nucleuscloud/neosync/backend/pkg/sqlmanager:
    interfaces:
      SqlDatabase:
      SqlManagerClient:
  github.com/nucleuscloud/neosync/internal/aws:
    interfaces:
      NeosyncAwsManagerClient:
      dynamoDBAPIV2:
  github.com/nucleuscloud/neosync/worker/pkg/workflows/datasync/activities/sync:
    interfaces:
      sqlProvider:
      sqlDbtx:
      BenthosStreamClient:
      BenthosStreamManagerClient:
  github.com/prometheus/client_golang/api/prometheus/v1:
    config:
      dir: "internal/mocks/{{.PackagePath}}"
      inpackage: False
      outpkg: promapiv1mock
    interfaces:
      API:
  github.com/nucleuscloud/neosync/backend/internal/loki:
    interfaces:
      LokiHttpClient:
  github.com/nucleuscloud/neosync/backend/pkg/mongoconnect:
    interfaces:
      Interface:
      DbContainer:
  github.com/nucleuscloud/neosync/backend/internal/gcp:
    interfaces:
      ManagerInterface:
      ClientInterface:
  github.com/nucleuscloud/neosync/internal/connection-manager:
    interfaces:
      ConnectionProvider:
  github.com/nucleuscloud/neosync/worker/pkg/benthos/dynamodb:
    interfaces:
      dynamoDBAPIV2:
  github.com/nucleuscloud/neosync/internal/billing:
    interfaces:
      Interface:
  github.com/jackc/pgx/v5:
    config:
      dir: "internal/mocks/{{.PackagePath}}"
      inpackage: False
      outpkg: pgxmock
    interfaces:
      Tx:
  github.com/nucleuscloud/neosync/internal/ee/presidio:
    interfaces:
      AnalyzeInterface:
      AnonymizeInterface:
      EntityInterface:
