quiet: False
disable-version-string: True
with-expecter: True
filename: 'mock_{{.InterfaceName}}.go'
dir: '{{.InterfaceDir}}'
mockname: 'Mock{{.InterfaceName}}'
outpkg: '{{.PackageName}}'
inpackage: True
packages:
  github.com/nucleuscloud/neosync/backend/internal/auth/jwt:
    # config:
    interfaces:
      JwtValidator:
  github.com/nucleuscloud/neosync/backend/internal/auth/authmw:
    interfaces:
      AuthClient:
  github.com/nucleuscloud/neosync/backend/internal/nucleusdb:
    # config:
    interfaces:
      DBTX:
  github.com/nucleuscloud/neosync/backend/gen/go/db:
    # config:
    interfaces:
      Querier:
      DBTX:
  github.com/nucleuscloud/neosync/backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect:
    # config:
    interfaces:
      UserAccountServiceClient:
      JobServiceClient:
      ConnectionServiceClient:
      AuthServiceClient:
      TransformersServiceClient:
  github.com/nucleuscloud/neosync/backend/internal/temporal/client-manager:
    interfaces:
      DB:
      # this is broken. it uses the wrong package. after running mockery change internal to client in mock
      # TemporalClientManagerClient:
  github.com/nucleuscloud/neosync/backend/gen/go/db/dbschemas/postgresql:
    # config:
    interfaces:
      Querier:
      DBTX:
  github.com/nucleuscloud/neosync/backend/gen/go/db/dbschemas/mysql:
    # config:
    interfaces:
      Querier:
      DBTX:
  github.com/nucleuscloud/neosync/backend/internal/authmgmt/auth0:
    interfaces:
      Auth0MgmtClientInterface:
  github.com/nucleuscloud/neosync/backend/internal/sqlconnect:
    interfaces:
      SqlConnector:
  github.com/nucleuscloud/neosync/backend/internal/aws:
    interfaces:
      NeosyncAwsManagerClient:
