quiet: False
disable-version-string: True
with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
  github.com/nucleuscloud/neosync/backend/internal/jwt:
    # config:
    interfaces:
      JwtValidator:
  github.com/nucleuscloud/neosync/backend/internal/nucleusdb:
    # config:
    interfaces:
      DBTX:
  github.com/nucleuscloud/neosync/backend/gen/go/db:
    # config:
    interfaces:
      Querier:
  github.com/nucleuscloud/neosync/backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect:
    # config:
    interfaces:
      UserAccountServiceClient:
      JobServiceClient:
      ConnectionServiceClient:
  github.com/nucleuscloud/neosync/backend/internal/temporal/client-manager:
    interfaces:
      DB:
  github.com/nucleuscloud/neosync/worker/gen/go/db/postgresql:
    # config:
    interfaces:
      Querier:
      DBTX:
  github.com/nucleuscloud/neosync/worker/gen/go/db/mysql:
    # config:
    interfaces:
      Querier:
      DBTX:
