quiet: False
disable-version-string: True
with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
  github.com/nucleuscloud/neosync/backend/internal/jwt:
    # config:
    interfaces:
      JwtValidator:
