image:
  repository: neosync-api

serviceAccount:
  create: true

db:
  host: neosync-postgresql
  name: nucleus
  port: 5432
  username: postgres
  password: foofar
  disableSsl: true

migrations:
  db:
    host: neosync-postgresql
    name: nucleus
    port: 5432
    username: postgres
    password: foofar
    disableSsl: true
    schemaDir: /app/migrations

terminationGracePeriodSeconds: 300
shutdownTimeoutSeconds: 5

istio:
  enabled: false

datadog:
  enabled: false

nucleusEnv: dev

servicePort: 80
containerPort: 8080

auth:
  baseUrl: https://auth.nucleuscloud.dev
  audience: https://api.nucleuscloud.com
  clientIdSecret:
    {
      "N53szkXwrMZmWiMQ96bJVCSuafn6myMR": "ZggNj5-HTCOdYzovNBZTDIys9sdLIl9aKOqn23yXMonECpG7N2qELVwQEfY_It5T",
    }
  cliClient: N53szkXwrMZmWiMQ96bJVCSuafn6myMR
  clientAudience: https://api.nucleuscloud.com
  apiBaseUrl: https://nucleus-cloud-dev.us.auth0.com
  apiClientId: NmymQDhFqcMS42Qc9s8zGCX52IoZcJy6
  apiClientSecret: UUAsnRJZ_fqw4qRgXCed6Q9rY7QgSuU170xY_Tbmr2kImi2WEI-IjoSzRDhR7X2A

temporal:
  url: temporal.temporal:7233
  namespace: default
  taskQueue: "sync-job"

ingress:
  enabled: false
