# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: presidioapi
output: client.gen.go
generate:
  client: true
  models: true

