apiVersion: v1
kind: PersistentVolume
metadata:
	name: redis-data-redis-master0
spec:
	capacity:
		storage: 8Gi
	accessModes:
		- ReadWriteOnce
	hostPath:
		path: "/storage/data-master0"

---
apiVersion: v1
kind: PersistentVolume
metadata:
	name: redis-data-redis-replicas0
spec:
	capacity:
		storage: 8Gi
	accessModes:
		- ReadWriteOnce
	hostPath:
		path: "/storage/data-replicas0"
