apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "neosync-api.fullname" . }}-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "neosync-api.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "neosync-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
