server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker_logs
          __path__: /var/log/docker/containers/*/*.log
    pipeline_stages:
      - cri:
      - docker:
      - json:
          expressions:
            level: level
            msg: msg
            namespace: Namespace
            runID: RunID
            time: time
            workflowID: WorkflowID
      - labels:
          level: null
          namespace: null
          runID: null
          time: null
          workflowID: null
      - output:
          source: msg
