# permissions for end users to view taskruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: taskrun-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-operator
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: taskrun-viewer-role
rules:
- apiGroups:
  - neosync.dev
  resources:
  - taskruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - neosync.dev
  resources:
  - taskruns/status
  verbs:
  - get
