apiVersion: v2
name: api
description: A Helm chart for the Neosync Backend API
home: https://www.neosync.dev
sources:
  - https://github.com/nucleuscloud/neosync
icon: https://assets.nucleuscloud.com/neosync/newbrand/logo_small.png
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version.
#
# This is changed automatically to the tag by the github workflow.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "v0"

appVersion: "v0"
