apiVersion: v1
kind: Secret
metadata:
    name: {{ template "neosync-app.fullname" . }}-service-evs
    namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
    {{- if .Values.host }}
    HOSTNAME: {{ .Values.host | quote}}
    {{- end }}

    PORT: {{ .Values.port | quote }}

    {{- if ne .Values.nucleusEnv "dev" }}
    OTEL_EXPORTER_OTLP_PORT: "4317" # sends to gRPC receiver on port 4317
    {{- end }}

    NUCLEUS_ENV: {{ .Values.nucleusEnv }}

    SHUTDOWN_TIMEOUT_SECONDS: {{ .Values.shutdownTimeoutSeconds | quote }}

    NEOSYNC_API_BASE_URL: {{ .Values.neosyncApi.url }}

    NEXTAUTH_SECRET: {{ .Values.nextAuthSecret }}

    {{ if .Values.nextAuthUrl }}
    NEXTAUTH_URL: {{ .Values.nextAuthUrl }}
    {{- end }}

    {{ if .Values.auth0.clientId }}
    AUTH0_CLIENT_ID: {{ .Values.auth0.clientId }}
    {{- end }}
    {{ if .Values.auth0.clientSecret }}
    AUTH0_CLIENT_SECRET: {{ .Values.auth0.clientSecret }}
    {{- end }}
    {{ if .Values.auth0.issuer }}
    AUTH0_ISSUER: {{ .Values.auth0.issuer }}
    {{- end }}
    {{ if .Values.auth0.scope }}
    AUTH0_SCOPE: {{ .Values.auth0.scope }}
    {{- end }}
    {{ if .Values.auth0.audience }}
    AUTH0_AUDIENCE: {{ .Values.auth0.audience }}
    {{- end }}

    AUTH_ENABLED: {{ .Values.auth.enabled | default "false" | quote }}
