services:
  app:
    container_name: neosync-app
    image: neosync-app
    build:
      context: $PWD/frontend
      dockerfile: ./apps/web/dev/build/Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - HOSTNAME=0.0.0.0
      - NUCLEUS_ENV=dev
      - NEXTAUTH_SECRET=foo
      - NEXTAUTH_URL=http://localhost:3000
      - NEOSYNC_API_BASE_URL=http://api:8080
      - NEXT_PUBLIC_APP_BASE_URL=http://localhost:3000

      - POSTHOG_KEY=phc_qju45RhNvCDwYVdRyUjtWuWsOmLFaQZi3fmztMBaJip

      - AUTH_ENABLED=true
      - AUTH_ISSUER=http://keycloak:8080/realms/neosync
      - AUTH_EXPECTED_ISSUER=http://localhost:8083/realms/neosync
      - AUTH_AUTHORIZE_URL=http://localhost:8083/realms/neosync/protocol/openid-connect/auth
      - AUTH_USERINFO_URL=http://keycloak:8080/realms/neosync/protocol/openid-connect/userinfo
      - AUTH_TOKEN_URL=http://keycloak:8080/realms/neosync/protocol/openid-connect/token

      - AUTH_CLIENT_ID=neosync-app
      - AUTH_CLIENT_SECRET=72alWGzhHInDskRHduTQ8BjB4Lgn0n3a
      - AUTH_AUDIENCE=neosync
      - AUTH_SCOPE=openid email profile offline_access
      - AUTH_PROVIDER_ID=keycloak
      - AUTH_PROVIDER_NAME=Keycloak

    networks:
      - neosync-network
      - kc-network
    develop:
      watch:
        - path: $PWD/frontend/package.json
          action: rebuild
        - path: $PWD/frontend/package-lock.json
          action: rebuild
        - path: $PWD/frontend/
          action: sync
          target: /app
          ignore:
            - $PWD/frontend/node_modules/

  db:
    container_name: neosync-db
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=nucleus
      - POSTGRES_PASSWORD=foofar
      - PGUSER=postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - neosync-network
      - kc-network
    volumes:
      - $PWD/.data/neosync-postgres/data:/var/lib/postgresql/data
      - $PWD/hack/pg-init:/docker-entrypoint-initdb.d

  api:
    container_name: neosync-api
    image: neosync-api
    build:
      context: $PWD/backend
      dockerfile: ./dev/build/Dockerfile.dev
    ports:
      - 8080:8080
    command: serve connect
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - NUCLEUS_ENV=dev
      - TEMPORAL_URL=temporal:7233
      - DB_AUTO_MIGRATE=true
      - DB_SCHEMA_DIR=/app/migrations
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=nucleus
      - DB_USER=postgres
      - DB_PASS=foofar
      - DB_SSL_DISABLE=true
      - DB_MIGRATIONS_TABLE=neosync_api_schema_migrations
      - DB_MIGRATIONS_TABLE_QUOTED=false

      - AUTH_ENABLED=true
      - AUTH_AUDIENCE=neosync
      - AUTH_BASEURL=http://keycloak:8080/realms/neosync
      - AUTH_EXPECTED_ISS=http://localhost:8083/realms/neosync
      - AUTH_CLI_CLIENT_ID=neosync-cli
      - AUTH_CLI_AUDIENCE=neosync
      - AUTH_CLIENTID_SECRET={"neosync-cli":"GkVsthDzDvBfzb2vT4UO95xbXrwoXE5w"}
      - AUTH_SIGNATURE_ALGORITHM=RS256

    networks:
      - neosync-network
      - temporal-network
      - kc-network

    depends_on:
      db:
        condition: service_healthy
        restart: true
    develop:
      watch:
        - path: $PWD/backend/bin
          action: sync+restart
          target: /app

  worker:
    container_name: neosync-worker
    image: neosync-worker
    build:
      context: $PWD/worker
      dockerfile: ./dev/build/Dockerfile.dev
    environment:
      - NUCLEUS_ENV=dev
      - TEMPORAL_URL=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_TASK_QUEUE=sync-job
      - NEOSYNC_URL=http://api:8080
    networks:
      - neosync-network
      - temporal-network
    develop:
      watch:
        - path: $PWD/worker/bin
          action: sync+restart
          target: /app

  keycloak:
    container_name: neosync-auth-keycloak
    image: quay.io/keycloak/keycloak
    ports:
      - 8083:8080
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=change_me

      - KC_HOSTNAME_URL=http://localhost:8083

      - KC_DB=postgres
      - KC_DB_URL_HOST=db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=nucleus
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=foofar
      - KC_DB_SCHEMA=keycloak
    volumes:
      - $PWD/keycloak/imports:/opt/keycloak/data/import
    networks:
      - kc-network
    depends_on:
      db:
        condition: service_healthy
        restart: true

networks:
  neosync-network:
    driver: bridge
    name: neosync-network
  kc-network:
    driver: bridge
    name: kc-network
  temporal-network:
    external: true
