
// Code generated by Neosync neosync_transformer_generator.go. DO NOT EDIT.
// source: transform_string_phone_number.go

package transformers

import (
	"fmt"
	
	transformer_utils "github.com/nucleuscloud/neosync/worker/pkg/benthos/transformers/utils"
	"github.com/nucleuscloud/neosync/worker/pkg/rng"
	
)

type TransformStringPhoneNumber struct{}

type TransformStringPhoneNumberOpts struct {
	randomizer     rng.Rand
	
	preserveLength bool
	maxLength int64
}

func NewTransformStringPhoneNumber() *TransformStringPhoneNumber {
	return &TransformStringPhoneNumber{}
}

func (t *TransformStringPhoneNumber) GetJsTemplateData() (*TemplateData, error) {
	return &TemplateData{
		Name: "transformStringPhoneNumber",
		Description: "Transforms an existing phone number that is typed as a string.",
		Example: "",
	}, nil
}

func (t *TransformStringPhoneNumber) ParseOptions(opts map[string]any) (any, error) {
	transformerOpts := &TransformStringPhoneNumberOpts{}

	if _, ok := opts["preserveLength"].(bool); !ok {
		return nil, fmt.Errorf("missing required argument. function: %s argument: %s", "transformStringPhoneNumber", "preserveLength")
	}
	preserveLength := opts["preserveLength"].(bool)
	transformerOpts.preserveLength = preserveLength

	if _, ok := opts["maxLength"].(int64); !ok {
		return nil, fmt.Errorf("missing required argument. function: %s argument: %s", "transformStringPhoneNumber", "maxLength")
	}
	maxLength := opts["maxLength"].(int64)
	transformerOpts.maxLength = maxLength

	var seed int64
	seedArg, ok := opts["seed"].(int64)
	if ok {
		seed = seedArg
	} else {
		var err error
		seed, err = transformer_utils.GenerateCryptoSeed()
		if err != nil {
			return nil, fmt.Errorf("unable to generate seed: %w", err)
		}
	}
	transformerOpts.randomizer = rng.New(seed)

	return transformerOpts, nil
}
