
// Code generated by Neosync neosync_transformer_generator.go. DO NOT EDIT.
// source: generate_zipcode.go

package transformers

import (
	"strings"
	"fmt"
	transformer_utils "github.com/nucleuscloud/neosync/worker/pkg/benthos/transformers/utils"
	"github.com/nucleuscloud/neosync/worker/pkg/rng"
	
)

type GenerateZipcode struct{}

type GenerateZipcodeOpts struct {
	randomizer     rng.Rand
	
}

func NewGenerateZipcode() *GenerateZipcode {
	return &GenerateZipcode{}
}

func NewGenerateZipcodeOpts(
  seedArg *int64,
) (*GenerateZipcodeOpts, error) {
	seed, err := transformer_utils.GetSeedOrDefault(seedArg)
  if err != nil {
    return nil, fmt.Errorf("unable to generate seed: %w", err)
	}
	
	return &GenerateZipcodeOpts{
		randomizer: rng.New(seed),
	}, nil
}

func (o *GenerateZipcodeOpts) BuildBloblangString(
) string {
	fnStr := []string{
	}

	params := []any{
	}

	

	template := fmt.Sprintf("generate_zipcode(%s)", strings.Join(fnStr, ","))
	return fmt.Sprintf(template, params...)
}

func (t *GenerateZipcode) GetJsTemplateData() (*TemplateData, error) {
	return &TemplateData{
		Name: "generateZipcode",
		Description: "Generates a randomly selected US zipcode.",
		Example: "",
	}, nil
}

func (t *GenerateZipcode) ParseOptions(opts map[string]any) (any, error) {
	transformerOpts := &GenerateZipcodeOpts{}

	var seedArg *int64
	if seedValue, ok := opts["seed"].(int64); ok {
			seedArg = &seedValue
	}
	seed, err := transformer_utils.GetSeedOrDefault(seedArg)
	if err != nil {
		return nil, fmt.Errorf("unable to generate seed: %w", err)
	}
	transformerOpts.randomizer = rng.New(seed)

	return transformerOpts, nil
}
