
// Code generated by Neosync neosync_transformer_generator.go. DO NOT EDIT.
// source: generate_international_phone_number.go

package transformers

import (
	"fmt"
	
	transformer_utils "github.com/nucleuscloud/neosync/worker/pkg/benthos/transformers/utils"
	"github.com/nucleuscloud/neosync/worker/pkg/rng"
	
)

type GenerateInternationalPhoneNumber struct{}

type GenerateInternationalPhoneNumberOpts struct {
	randomizer     rng.Rand
	
	min int64
	max int64
}

func NewGenerateInternationalPhoneNumber() *GenerateInternationalPhoneNumber {
	return &GenerateInternationalPhoneNumber{}
}

func NewGenerateInternationalPhoneNumberOpts(
	min int64,
	max int64,
  seedArg *int64,
) (*GenerateInternationalPhoneNumberOpts, error) {
	seed, err := transformer_utils.GetSeedOrDefault(seedArg)
  if err != nil {
    return nil, fmt.Errorf("unable to generate seed: %w", err)
	}
	
	return &GenerateInternationalPhoneNumberOpts{
		min: min,
		max: max,
		randomizer: rng.New(seed),	
	}, nil
}

func (t *GenerateInternationalPhoneNumber) GetJsTemplateData() (*TemplateData, error) {
	return &TemplateData{
		Name: "generateInternationalPhoneNumber",
		Description: "Generates a new random international phone number including the + sign and no hyphens.",
		Example: "",
	}, nil
}

func (t *GenerateInternationalPhoneNumber) ParseOptions(opts map[string]any) (any, error) {
	transformerOpts := &GenerateInternationalPhoneNumberOpts{}

	if _, ok := opts["min"].(int64); !ok {
		return nil, fmt.Errorf("missing required argument. function: %s argument: %s", "generateInternationalPhoneNumber", "min")
	}
	min := opts["min"].(int64)
	transformerOpts.min = min

	if _, ok := opts["max"].(int64); !ok {
		return nil, fmt.Errorf("missing required argument. function: %s argument: %s", "generateInternationalPhoneNumber", "max")
	}
	max := opts["max"].(int64)
	transformerOpts.max = max

	var seedArg *int64
	if seedValue, ok := opts["seed"].(int64); ok {
			seedArg = &seedValue
	}
	seed, err := transformer_utils.GetSeedOrDefault(seedArg)
	if err != nil {
		return nil, fmt.Errorf("unable to generate seed: %w", err)
	}
	transformerOpts.randomizer = rng.New(seed)

	return transformerOpts, nil
}
