
// Code generated by Neosync neosync_transformer_generator.go. DO NOT EDIT.
// source: generate_street_address.go

package transformers

import (
	"fmt"
	
)

type GenerateStreetAddress struct{}

type GenerateStreetAddressOpts struct {
	maxLength int64
}

func NewGenerateStreetAddress() *GenerateStreetAddress {
	return &GenerateStreetAddress{}
}

func (t *GenerateStreetAddress) GetJsTemplateData() (*TemplateData, error) {
	return &TemplateData{
		Name: "generateStreetAddress",
		Description: "",
		Example: "",
	}, nil
}

func (t *GenerateStreetAddress) ParseOptions(opts map[string]any) (any, error) {
	transformerOpts := &GenerateStreetAddressOpts{}

	if _, ok := opts["maxLength"].(int64); !ok {
		return nil, fmt.Errorf("missing required argument. function: %s argument: %s", "generateStreetAddress", "maxLength")
	}
	maxLength := opts["maxLength"].(int64)
	transformerOpts.maxLength = maxLength

	return transformerOpts, nil
}
