
// Code generated by Neosync neosync_transformer_generator.go. DO NOT EDIT.
// source: generate_full_address.go

package transformers

import (
	"strings"
	"fmt"
	transformer_utils "github.com/nucleuscloud/neosync/worker/pkg/benthos/transformers/utils"
	"github.com/nucleuscloud/neosync/worker/pkg/rng"
	
)

type GenerateFullAddress struct{}

type GenerateFullAddressOpts struct {
	randomizer     rng.Rand
	
	maxLength int64
}

func NewGenerateFullAddress() *GenerateFullAddress {
	return &GenerateFullAddress{}
}

func NewGenerateFullAddressOpts(
	maxLengthArg *int64,
  seedArg *int64,
) (*GenerateFullAddressOpts, error) {
	maxLength := int64(100)
	if maxLengthArg != nil {
		maxLength = *maxLengthArg
	}
	
	seed, err := transformer_utils.GetSeedOrDefault(seedArg)
  if err != nil {
    return nil, fmt.Errorf("unable to generate seed: %w", err)
	}
	
	return &GenerateFullAddressOpts{
		maxLength: maxLength,
		randomizer: rng.New(seed),
	}, nil
}

func (o *GenerateFullAddressOpts) BuildBloblangString(
) string {
	fnStr := []string{
		"max_length:%v",
	}

	params := []any{
	 	o.maxLength,
	}

	

	template := fmt.Sprintf("generate_full_address(%s)", strings.Join(fnStr, ","))
	return fmt.Sprintf(template, params...)
}

func (t *GenerateFullAddress) GetJsTemplateData() (*TemplateData, error) {
	return &TemplateData{
		Name: "generateFullAddress",
		Description: "Generates a randomly selected real full address that exists in the United States.",
		Example: "",
	}, nil
}

func (t *GenerateFullAddress) ParseOptions(opts map[string]any) (any, error) {
	transformerOpts := &GenerateFullAddressOpts{}

	maxLength, ok := opts["maxLength"].(int64)
	if !ok {
		maxLength = 100
	}
	transformerOpts.maxLength = maxLength

	var seedArg *int64
	if seedValue, ok := opts["seed"].(int64); ok {
			seedArg = &seedValue
	}
	seed, err := transformer_utils.GetSeedOrDefault(seedArg)
	if err != nil {
		return nil, fmt.Errorf("unable to generate seed: %w", err)
	}
	transformerOpts.randomizer = rng.New(seed)

	return transformerOpts, nil
}
