quiet: False
disable-version-string: True
with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
  github.com/nucleuscloud/neosync/worker/pkg/workflows/datasync/activities/sync:
    interfaces:
      sqlProvider:
      sqlDbtx:
