package transformers_dataset

type Country struct {
	Code     string
	FullName string
}

var Countries = []Country{
	{Code: "AF", FullName: "Afghanistan"},
	{Code: "AL", FullName: "Albania"},
	{Code: "DZ", FullName: "Algeria"},
	{Code: "AS", FullName: "American Samoa"},
	{Code: "AD", FullName: "Andorra"},
	{Code: "AO", FullName: "Angola"},
	{Code: "AI", FullName: "Anguilla"},
	{Code: "AQ", FullName: "Antarctica"},
	{Code: "AG", FullName: "Antigua and Barbuda"},
	{Code: "AR", FullName: "Argentina"},
	{Code: "AM", FullName: "Armenia"},
	{Code: "AW", FullName: "Aruba"},
	{Code: "AU", FullName: "Australia"},
	{Code: "AT", FullName: "Austria"},
	{Code: "AZ", FullName: "Azerbaijan"},
	{Code: "BS", FullName: "Bahamas"},
	{Code: "BH", FullName: "Bahrain"},
	{Code: "BD", FullName: "Bangladesh"},
	{Code: "BB", FullName: "Barbados"},
	{Code: "BY", FullName: "Belarus"},
	{Code: "BE", FullName: "Belgium"},
	{Code: "BZ", FullName: "Belize"},
	{Code: "BJ", FullName: "Benin"},
	{Code: "BM", FullName: "Bermuda"},
	{Code: "BT", FullName: "Bhutan"},
	{Code: "BO", FullName: "Bolivia"},
	{Code: "BA", FullName: "Bosnia and Herzegovina"},
	{Code: "BW", FullName: "Botswana"},
	{Code: "BR", FullName: "Brazil"},
	{Code: "IO", FullName: "British Indian Ocean Territory"},
	{Code: "BN", FullName: "Brunei Darussalam"},
	{Code: "BG", FullName: "Bulgaria"},
	{Code: "BF", FullName: "Burkina Faso"},
	{Code: "BI", FullName: "Burundi"},
	{Code: "CV", FullName: "Cabo Verde"},
	{Code: "KH", FullName: "Cambodia"},
	{Code: "CM", FullName: "Cameroon"},
	{Code: "CA", FullName: "Canada"},
	{Code: "KY", FullName: "Cayman Islands"},
	{Code: "CF", FullName: "Central African Republic"},
	{Code: "TD", FullName: "Chad"},
	{Code: "CL", FullName: "Chile"},
	{Code: "CN", FullName: "China"},
	{Code: "CO", FullName: "Colombia"},
	{Code: "KM", FullName: "Comoros"},
	{Code: "CG", FullName: "Congo"},
	{Code: "CD", FullName: "Congo, Democratic Republic of the"},
	{Code: "CK", FullName: "Cook Islands"},
	{Code: "CR", FullName: "Costa Rica"},
	{Code: "CI", FullName: "Côte d'Ivoire"},
	{Code: "HR", FullName: "Croatia"},
	{Code: "CU", FullName: "Cuba"},
	{Code: "CY", FullName: "Cyprus"},
	{Code: "CZ", FullName: "Czechia"},
	{Code: "DK", FullName: "Denmark"},
	{Code: "DJ", FullName: "Djibouti"},
	{Code: "DM", FullName: "Dominica"},
	{Code: "DO", FullName: "Dominican Republic"},
	{Code: "EC", FullName: "Ecuador"},
	{Code: "EG", FullName: "Egypt"},
	{Code: "SV", FullName: "El Salvador"},
	{Code: "GQ", FullName: "Equatorial Guinea"},
	{Code: "ER", FullName: "Eritrea"},
	{Code: "EE", FullName: "Estonia"},
	{Code: "SZ", FullName: "Eswatini"},
	{Code: "ET", FullName: "Ethiopia"},
	{Code: "FJ", FullName: "Fiji"},
	{Code: "FI", FullName: "Finland"},
	{Code: "FR", FullName: "France"},
	{Code: "GA", FullName: "Gabon"},
	{Code: "GM", FullName: "Gambia"},
	{Code: "GE", FullName: "Georgia"},
	{Code: "DE", FullName: "Germany"},
	{Code: "GH", FullName: "Ghana"},
	{Code: "GI", FullName: "Gibraltar"},
	{Code: "GR", FullName: "Greece"},
	{Code: "GL", FullName: "Greenland"},
	{Code: "GD", FullName: "Grenada"},
	{Code: "GU", FullName: "Guam"},
	{Code: "GT", FullName: "Guatemala"},
	{Code: "GG", FullName: "Guernsey"},
	{Code: "GN", FullName: "Guinea"},
	{Code: "GW", FullName: "Guinea-Bissau"},
	{Code: "GY", FullName: "Guyana"},
	{Code: "HT", FullName: "Haiti"},
	{Code: "HN", FullName: "Honduras"},
	{Code: "HK", FullName: "Hong Kong"},
	{Code: "HU", FullName: "Hungary"},
	{Code: "IS", FullName: "Iceland"},
	{Code: "IN", FullName: "India"},
	{Code: "ID", FullName: "Indonesia"},
	{Code: "IR", FullName: "Iran, Islamic Republic of"},
	{Code: "IQ", FullName: "Iraq"},
	{Code: "IE", FullName: "Ireland"},
	{Code: "IM", FullName: "Isle of Man"},
	{Code: "IL", FullName: "Israel"},
	{Code: "IT", FullName: "Italy"},
	{Code: "JM", FullName: "Jamaica"},
	{Code: "JP", FullName: "Japan"},
	{Code: "JE", FullName: "Jersey"},
	{Code: "JO", FullName: "Jordan"},
	{Code: "KZ", FullName: "Kazakhstan"},
	{Code: "KE", FullName: "Kenya"},
	{Code: "KI", FullName: "Kiribati"},
	{Code: "KP", FullName: "Korea, Democratic People's Republic of"},
	{Code: "KR", FullName: "Korea, Republic of"},
	{Code: "KW", FullName: "Kuwait"},
	{Code: "KG", FullName: "Kyrgyzstan"},
	{Code: "LA", FullName: "Lao People's Democratic Republic"},
	{Code: "LV", FullName: "Latvia"},
	{Code: "LB", FullName: "Lebanon"},
	{Code: "LS", FullName: "Lesotho"},
	{Code: "LR", FullName: "Liberia"},
	{Code: "LY", FullName: "Libya"},
	{Code: "LI", FullName: "Liechtenstein"},
	{Code: "LT", FullName: "Lithuania"},
	{Code: "LU", FullName: "Luxembourg"},
	{Code: "MO", FullName: "Macao"},
	{Code: "MG", FullName: "Madagascar"},
	{Code: "MW", FullName: "Malawi"},
	{Code: "MY", FullName: "Malaysia"},
	{Code: "MV", FullName: "Maldives"},
	{Code: "ML", FullName: "Mali"},
	{Code: "MT", FullName: "Malta"},
	{Code: "MH", FullName: "Marshall Islands"},
	{Code: "MR", FullName: "Mauritania"},
	{Code: "MU", FullName: "Mauritius"},
	{Code: "MX", FullName: "Mexico"},
	{Code: "FM", FullName: "Micronesia (Federated States of)"},
	{Code: "MD", FullName: "Moldova, Republic of"},
	{Code: "MC", FullName: "Monaco"},
	{Code: "MN", FullName: "Mongolia"},
	{Code: "ME", FullName: "Montenegro"},
	{Code: "MS", FullName: "Montserrat"},
	{Code: "MA", FullName: "Morocco"},
	{Code: "MZ", FullName: "Mozambique"},
	{Code: "MM", FullName: "Myanmar"},
	{Code: "NA", FullName: "Namibia"},
	{Code: "NR", FullName: "Nauru"},
	{Code: "NP", FullName: "Nepal"},
	{Code: "NL", FullName: "Netherlands"},
	{Code: "NC", FullName: "New Caledonia"},
	{Code: "NZ", FullName: "New Zealand"},
	{Code: "NI", FullName: "Nicaragua"},
	{Code: "NE", FullName: "Niger"},
	{Code: "NG", FullName: "Nigeria"},
	{Code: "NU", FullName: "Niue"},
	{Code: "NF", FullName: "Norfolk Island"},
	{Code: "MK", FullName: "North Macedonia"},
	{Code: "MP", FullName: "Northern Mariana Islands"},
	{Code: "NO", FullName: "Norway"},
	{Code: "OM", FullName: "Oman"},
	{Code: "PK", FullName: "Pakistan"},
	{Code: "PW", FullName: "Palau"},
	{Code: "PS", FullName: "Palestine, State of"},
	{Code: "PA", FullName: "Panama"},
	{Code: "PG", FullName: "Papua New Guinea"},
	{Code: "PY", FullName: "Paraguay"},
	{Code: "PE", FullName: "Peru"},
	{Code: "PH", FullName: "Philippines"},
	{Code: "PL", FullName: "Poland"},
	{Code: "PT", FullName: "Portugal"},
	{Code: "PR", FullName: "Puerto Rico"},
	{Code: "QA", FullName: "Qatar"},
	{Code: "RO", FullName: "Romania"},
	{Code: "RU", FullName: "Russian Federation"},
	{Code: "RW", FullName: "Rwanda"},
	{Code: "WS", FullName: "Samoa"},
	{Code: "SM", FullName: "San Marino"},
	{Code: "ST", FullName: "Sao Tome and Principe"},
	{Code: "SA", FullName: "Saudi Arabia"},
	{Code: "SN", FullName: "Senegal"},
	{Code: "RS", FullName: "Serbia"},
	{Code: "SC", FullName: "Seychelles"},
	{Code: "SL", FullName: "Sierra Leone"},
	{Code: "SG", FullName: "Singapore"},
	{Code: "SX", FullName: "Sint Maarten (Dutch part)"},
	{Code: "SK", FullName: "Slovakia"},
	{Code: "SI", FullName: "Slovenia"},
	{Code: "SB", FullName: "Solomon Islands"},
	{Code: "SO", FullName: "Somalia"},
	{Code: "ZA", FullName: "South Africa"},
	{Code: "SS", FullName: "South Sudan"},
	{Code: "ES", FullName: "Spain"},
	{Code: "LK", FullName: "Sri Lanka"},
	{Code: "SD", FullName: "Sudan"},
	{Code: "SR", FullName: "Suriname"},
	{Code: "SE", FullName: "Sweden"},
	{Code: "CH", FullName: "Switzerland"},
	{Code: "SY", FullName: "Syrian Arab Republic"},
	{Code: "TW", FullName: "Taiwan, Province of China"},
	{Code: "TJ", FullName: "Tajikistan"},
	{Code: "TZ", FullName: "Tanzania, United Republic of"},
	{Code: "TH", FullName: "Thailand"},
	{Code: "TL", FullName: "Timor-Leste"},
	{Code: "TG", FullName: "Togo"},
	{Code: "TK", FullName: "Tokelau"},
	{Code: "TO", FullName: "Tonga"},
	{Code: "TT", FullName: "Trinidad and Tobago"},
	{Code: "TN", FullName: "Tunisia"},
	{Code: "TR", FullName: "Turkey"},
	{Code: "TM", FullName: "Turkmenistan"},
	{Code: "TV", FullName: "Tuvalu"},
	{Code: "UG", FullName: "Uganda"},
	{Code: "UA", FullName: "Ukraine"},
	{Code: "AE", FullName: "United Arab Emirates"},
	{Code: "GB", FullName: "United Kingdom"},
	{Code: "US", FullName: "United States of America"},
	{Code: "UY", FullName: "Uruguay"},
	{Code: "UZ", FullName: "Uzbekistan"},
	{Code: "VU", FullName: "Vanuatu"},
	{Code: "VE", FullName: "Venezuela (Bolivarian Republic of)"},
	{Code: "VN", FullName: "Viet Nam"},
	{Code: "WF", FullName: "Wallis and Futuna"},
	{Code: "EH", FullName: "Western Sahara"},
	{Code: "YE", FullName: "Yemen"},
	{Code: "ZM", FullName: "Zambia"},
	{Code: "ZW", FullName: "Zimbabwe"},
}
