package transformers_dataset

type State struct {
	Code     string
	FullName string
}

var States = []State{
	{Code: "AL", FullName: "Alabama"},
	{Code: "AK", FullName: "Alaska"},
	{Code: "AZ", FullName: "Arizona"},
	{Code: "AR", FullName: "Arkansas"},
	{Code: "CA", FullName: "California"},
	{Code: "CO", FullName: "Colorado"},
	{Code: "CT", FullName: "Connecticut"},
	{Code: "DE", FullName: "Delaware"},
	{Code: "FL", FullName: "Florida"},
	{Code: "GA", FullName: "Georgia"},
	{Code: "HI", FullName: "Hawaii"},
	{Code: "ID", FullName: "Idaho"},
	{Code: "IL", FullName: "Illinois"},
	{Code: "IN", FullName: "Indiana"},
	{Code: "IA", FullName: "Iowa"},
	{Code: "KS", FullName: "Kansas"},
	{Code: "KY", FullName: "Kentucky"},
	{Code: "LA", FullName: "Louisiana"},
	{Code: "ME", FullName: "Maine"},
	{Code: "MD", FullName: "Maryland"},
	{Code: "MA", FullName: "Massachusetts"},
	{Code: "MI", FullName: "Michigan"},
	{Code: "MN", FullName: "Minnesota"},
	{Code: "MS", FullName: "Mississippi"},
	{Code: "MO", FullName: "Missouri"},
	{Code: "MT", FullName: "Montana"},
	{Code: "NE", FullName: "Nebraska"},
	{Code: "NV", FullName: "Nevada"},
	{Code: "NH", FullName: "New Hampshire"},
	{Code: "NJ", FullName: "New Jersey"},
	{Code: "NM", FullName: "New Mexico"},
	{Code: "NY", FullName: "New York"},
	{Code: "NC", FullName: "North Carolina"},
	{Code: "ND", FullName: "North Dakota"},
	{Code: "OH", FullName: "Ohio"},
	{Code: "OK", FullName: "Oklahoma"},
	{Code: "OR", FullName: "Oregon"},
	{Code: "PA", FullName: "Pennsylvania"},
	{Code: "RI", FullName: "Rhode Island"},
	{Code: "SC", FullName: "South Carolina"},
	{Code: "SD", FullName: "South Dakota"},
	{Code: "TN", FullName: "Tennessee"},
	{Code: "TX", FullName: "Texas"},
	{Code: "UT", FullName: "Utah"},
	{Code: "VT", FullName: "Vermont"},
	{Code: "VA", FullName: "Virginia"},
	{Code: "WA", FullName: "Washington"},
	{Code: "WV", FullName: "West Virginia"},
	{Code: "WI", FullName: "Wisconsin"},
	{Code: "WY", FullName: "Wyoming"},
}
