load('ext://helm_resource', 'helm_resource', 'helm_repo')

helm_repo('metrics-server-repo', 'https://kubernetes-sigs.github.io/metrics-server/')
helm_resource('metrics-server', 'ms/metrics-server', resource_deps=['metrics-server-repo'], namespace="kube-system", flags=[
  "--set", "args[0]=--kubelet-insecure-tls",
  # "--set", "args[1]=--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"
])
