apiVersion: neosync.dev/v1alpha1
kind: JobConfig
metadata:
  labels:
    app.kubernetes.io/name: jobconfig
    app.kubernetes.io/instance: jobconfig-sample
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-operator
  name: jobconfig-sample
spec:
  # TODO(user): Add fields here
