apiVersion: neosync.dev/v1alpha1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: task
    app.kubernetes.io/instance: task-sample
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-operator
  name: task-sample
spec:
  # TODO(user): Add fields here
