apiVersion: neosync.dev/v1alpha1
kind: SqlConnection
metadata:
  name: prod
spec:
  driver: postgres
  url:
    valueFrom:
      secretKeyRef:
        name: prod-pg-creds
        key: url
---
apiVersion: v1
kind: Secret
metadata:
  name: prod-pg-creds
stringData:
  url: postgres://postgres:foofar@postgresql1:5432/neosync?sslmode=disable
---
apiVersion: neosync.dev/v1alpha1
kind: SqlConnection
metadata:
  name: stage
spec:
  driver: postgres
  url:
    value: postgres://postgres:foofar@postgresql2:5432/neosync?sslmode=disable
---
apiVersion: neosync.dev/v1alpha1
kind: JobConfig
metadata:
  name: prod-to-stage-sync
spec:
  source:
    sql:
      connectionRef:
        name: prod
      haltOnSchemaChange: true
      schemas:
        - schema: neosync_api
          table: users
          columns:
            - name: id
              transformer:
                name: uuid_v4
            # - name: first_name
            # - name: last_name
            # - name: email
            #   transformer:
            #     name: email
            - name: created_at
              # exclude: true
            - name: updated_at
        - schema: neosync_api
          table: accounts
          columns:
            - name: id
              transformer:
                name: uuid_v4
            - name: created_at
            - name: updated_at
            - name: account_type
            - name: account_slug
              transformer:
                name: name


  destinations:
    - sql:
        connectionRef:
          name: stage
        # truncate_before_insert: true # default
        # init_db_schema: true # run create table statements
---
