
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
stringData:
  benthos.yaml: |
    http:
      address: localhost:4195
    input:
      label: ""
      generate:
        mapping: |
          root = if random_int() % 2 == 0 {
            {
              "type": "foo",
              "foo": "is yummy"
            }
          } else {
            {
              "type": "bar",
              "bar": "is gross"
            }
          }
        interval: 1s
        count: 10
        batch_size: 1
    output:
      label: ""
      stdout:
        codec: lines
---
apiVersion: neosync.dev/v1alpha1
kind: JobRun
metadata:
  name: foo
spec:

---
apiVersion: neosync.dev/v1alpha1
kind: JobRunTask
metadata:
  labels:
    app.kubernetes.io/name: jobruntask
    app.kubernetes.io/instance: jobruntask-sample
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-operator
  name: jobruntask-sample
spec:
  runConfig:
    benthos:
      configFrom:
        secretKeyRef:
          name: my-secret
          key: benthos.yaml
---
apiVersion: neosync.dev/v1alpha1
kind: JobRunTask
metadata:
  labels:
    app.kubernetes.io/name: jobruntask
    app.kubernetes.io/instance: jobruntask-sample
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-operator
  name: jobruntask-sample2
spec:
  depends_on:
    - jobruntask-sample
  runConfig:
    benthos:
      configFrom:
        secretKeyRef:
          name: my-secret2
          key: benthos.yaml
