apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "neosync-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neosync-api.labels" . | nindent 4 }}
    {{- if eq .Values.datadog.enabled true }}
    tags.datadoghq.com/env: {{ .Values.nucleusEnv }}
    tags.datadoghq.com/service: {{ template "neosync-api.fullname" . }}
    tags.datadoghq.com/version: {{ .Values.image.tag | default .Chart.AppVersion  }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "neosync-api.fullname" . }}
  replicas: 1
  template:
    metadata:
      annotations:
        {{- if eq .Values.datadog.enabled true }}
        ad.datadoghq.com/nucleus-api.logs: '[{"source":"nucleus-neosync-api","service":"{{ template "neosync-api.fullname" . }}"}]'
        {{- end }}
        {{- if eq .Values.istio.enabled true }}
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
        {{- end }}
        rollme: {{ randAlphaNum 5 | quote }} # causes deployment to always roll on helm upgrade
      labels:
        {{- include "neosync-api.labels" . | nindent 8 }}
        app: {{ template "neosync-api.fullname" . }}
        {{- if eq .Values.istio.enabled true }}
        sidecar.istio.io/inject: "true"
        {{- end }}
        {{- if eq .Values.datadog.enabled true }}
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env: {{ .Values.nucleusEnv }}
        tags.datadoghq.com/service: {{ template "neosync-api.fullname" . }}
        tags.datadoghq.com/version: {{ .Values.image.tag | default .Chart.AppVersion  }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "neosync-api.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.terminationGracePeriod }}
      terminationGracePeriod: {{ .Values.terminationGracePeriod }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}

      initContainers:
        - name: db-migration
          image: '{{ .Values.image.repository | default "ghcr.io/nucleuscloud/neosync/api" }}:{{ .Values.image.tag | default .Chart.AppVersion  }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - migrate
            - up

          envFrom:
            - secretRef:
                name: {{ template "neosync-api.fullname" . }}-migration-evs

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: user-container
          image: '{{ .Values.image.repository | default "ghcr.io/nucleuscloud/neosync/api" }}:{{ .Values.image.tag | default .Chart.AppVersion  }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - serve
            - connect
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: grpc
              protocol: TCP
          livenessProbe:
            grpc:
              port: {{ .Values.containerPort}}
            periodSeconds: 2
            failureThreshold: 2
            successThreshold: 1
          readinessProbe:
            grpc:
              port: {{ .Values.containerPort }}
            periodSeconds: 2
            failureThreshold: 2
            successThreshold: 1
            initialDelaySeconds: 1

          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            {{- if eq .Values.datadog.enabled true }}
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            {{- end }}

            {{- with .Values.extraEnvVars }}
            {{- range .}}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- if .valueFrom.secretKeyRef }}
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
                {{- end }}
                {{- if .valueFrom.configMapKeyRef }}
                configMapKeyRef:
                  name: {{ .valueFrom.configMapKeyRef.name }}
                  key: {{ .valueFrom.configMapKeyRef.key }}
                {{- end }}
                {{- if .valueFrom.fieldRef }}
                fieldRef:
                  fieldPath: {{ .valueFrom.fieldRef.fieldPath }}
                {{- end }}
              {{- end }}
            {{- end }}
            {{- end }}

          envFrom:
            - secretRef:
                name: {{ template "neosync-api.fullname" . }}-service-evs
          # {{- if eq .Values.nucleusEnv "dev" }} # config created by Tilt; keep this at the bottom to override
          #   - configMapRef:
          #       name: dev-config
          # {{- end }}

      {{- if .Values.sidecarContainers }}
      {{- toYaml .Values.sidecarContainers | nindent 8 }}
      {{- end }}

  {{- if .Values.updateStrategy }}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
