name: Artifact Release Test

on:
  pull_request:

jobs:
  docker-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/nucleuscloud/neosync/api
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern={{raw}}
            type=sha

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - uses: depot/build-push-action@v1
        with:
          # push: ${{ github.event_name != 'pull_request' }}
          push: true
          platforms: linux/amd64,linux/arm64
          # tags: ${{ steps.meta.output.tags }}
          tags: ghcr.io/nucleuscloud/neosync/api:test
          # labels: ${{ steps.meta.outputs.labels }}
          context: .
          file: docker/Dockerfile.backend
