on:
  pull_request:
    paths:
      - frontend/**

name: Frontend
jobs:
  knip:
    name: Knip
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          package_json_file: frontend/package.json

      - run: pnpm ci
      - run: pnpm run knip:production

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          package_json_file: frontend/package.json

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: prettier-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: pnpm ci
      - run: pnpm run prettier:check

  build:
    name: TS Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          package_json_file: frontend/package.json

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - run: pnpm ci
      - name: Build
        run: pnpm run build
