on:
  pull_request:
    paths:
      - charts/**
      - backend/charts/**
      - worker/charts/**
      - frontend/apps/web/charts/**

name: Helm
jobs:
  lint:
    name: Check Helm Readmes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Docs
        run: |
          make helm/docs
          if ! git diff --exit-code; then
              echo "Documentation not up to date. Please run helm-docs and commit changes!" >&2
              exit 1
          fi
