on:
  pull_request:
    paths:
      - k8s-operator/**

name: Operator
jobs:
  golangci:
    name: golang-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: k8s-operator
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.REPO_PAT }}:x-oauth-basic@github.com/nucleuscloud".insteadOf "https://github.com/nucleuscloud"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: k8s-operator/go.mod
          cache-dependency-path: k8s-operator/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
          working-directory: k8s-operator

  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: k8s-operator
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.REPO_PAT }}:x-oauth-basic@github.com/nucleuscloud".insteadOf "https://github.com/nucleuscloud"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: k8s-operator/go.mod
          cache-dependency-path: k8s-operator/go.sum

      - name: Test
        run: |
          make test
