name: Python SDK Test

on:
  pull_request:

jobs:
  py-sdk-build:
    name: Python SDK Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build SDK
        run: |
          python -m pip install build
          python -m build
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: 0.4.80
      - uses: actions/upload-artifact@v4
        with:
          name: py-package
          path: python/dist/

  py-sdk-publish:
    name: Python SDK Publish
    runs-on: ubuntu-latest
    needs:
      - py-sdk-build
    permissions:
      id-token: write
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: py-package
          path: python/dist/
      - name: Publish release distributions to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
          packages-dir: python/dist/
