on:
  pull_request:
    paths:
      - worker/**

name: Worker
jobs:
  golangci:
    name: golang-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: worker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: worker/go.mod
          cache-dependency-path: worker/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
          working-directory: worker

  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: worker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: worker/go.mod
          cache-dependency-path: worker/go.sum

      - name: Test
        run: |
          go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
